name: Zomato Web App CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code in your repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Clone external Zomato Web App repository
    - name: Clone Zomato Web App
      run: |
        git clone https://github.com/SreekanthJaladanki/zomato-web-app.git
        cd zomato-web-app

    # Step 3: Install dependencies (Assuming this is a Node.js project; adjust as needed)
    - name: Install dependencies
      run: |
        cd zomato-web-app
        npm install

    # Step 4: Run the tests (Assuming `npm test` is the test command)
    - name: Run tests
      run: |
        cd zomato-web-app
        npm test

        
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        # cache: maven
    - name: FireFlink suite execution  
      run: java -jar fireflink-action-1.0.0.jar https://app.fireflink.com SUITE1001 E10C861BB4ED62B91DEAB64A51411AC1A6B98B33634C8C467B2A8DDE85571D0D98D45F22C8CB3C93 praveen.b@fireflink.com Web "&" Mobile
